---
# Ansible Playbook to Install Current Applications

- name: Install All Applications
  hosts: localhost
  tasks:
  - name: Install XYZ Application
    git:
      repo: https://github.com/concat/xyz.git
      dest: /var/www/xyz
      clone: yes
      update: yes
  - name: Install UVW Application
    git:
      repo: https://github.com/concat/uvw.git
      dest: /var/www/uvw
      clone: yes
      update: yes
...
